### ISSUE TITLE
Error fetching station

### ISSUE THREAD

**Issue by mhermens123** [qistoph/MMM-nstreinen#10]
After MMM-pir-sensor wake-up the MMM-nstreinen cannot load data.
error:  Error fetching station: Error: read ECONNRESET

when refreshing magicmirror manually through MMM-Remotecontrol it works fine again,

cant find the problem :(

**Comment by mhermens123** [comment]
apparently it's not a MMM-nstreinen problem but a wifi problem. but only the nstreinen module has issues with it. i placed the router closer and the problem was solved

**Comment by SemicolonStruggles** [comment]
I very rarely see this error but ocasionally i do get this error aswell. It would be nice to see a feature to auto reload the module every day or so.

**Comment by mhermens123** [comment]
i also get the error: Error fetching station: Error: getaddrinfo EAI_AGAIN webservices.ns.nl:80
this is after my mirror turns off the display(MMM-pir sensor

**Comment by qistoph** [comment]
Feel free to reopen the issue if the same error occurs.
