### ISSUE TITLE
Train delay traveladvice gone

### ISSUE THREAD

**Issue by mhermens123** [qistoph/MMM-nstreinen#11]
For example the train is leaving 12:00 but has +12 minutes delay. The traveladvice (trip) is gone when it's 12:01. Is it possible to calculate the delay? or show the previous trip?

**Comment by qistoph** [comment]
The NS API does not return these trains when searching for trips.

So that would mean we would have to request trips from an earlier time, (now-30 min?) and check if there are any delays that are still to depart.

If anyone's interested in giving this a try, feel free and please send a PR.

**Comment by mhermens123** [comment]
i fixed the problem by changinge the departureOffset
