### ISSUE TITLE
Module stuck after a while

### ISSUE THREAD

**Issue by SemicolonStruggles** [qistoph/MMM-nstreinen#12]
This has basically been an issue for the past year or so. Not sure why I didnt report it earlier.

After a certain amount of days the module will just get stuck and will no longer update the trips. There doesn't seem to be a pattern as to when it gets stuck. Sometimes it's a few days, sometimes more like weeks.

There also is no connection between the times at which it gets stuck. 6:12AM or 7:11PM, it appears to be completely random.

There is a simple workaround and that is just rebooting the magic mirror. While this fixes the issue temporarily this obviously is not the intended behaviour.

**Comment by maximoei** [comment]
Seems that if the modules loses internet connection (or API times out, etc.) once, it does not recover after that, but stays stuck until restarting MMM.

There should be some logic to recover and retry I guess

**Comment by qistoph** [comment]
Thanks @maximoei for this addition. Did you find a consistent method to reproduce the error?

**Comment by qistoph** [comment]
Feel free to reopen the issue if the same error occurs.

**Comment by SemicolonStruggles** [comment]
Thank you! Will let you know if the problem persists.
