### ISSUE TITLE
Module doesn't show

### ISSUE THREAD

**Issue by JeroenV99** [qistoph/MMM-nstreinen#16]
the files are in the moved to the modules folder
installled them
i have setup the config file

but nothing on screens happen?

**Comment by JeroenV99** [comment]
![image](https://user-images.githubusercontent.com/35964877/54784780-f4bbe900-4c24-11e9-9183-9a251e30907c.png)

**Comment by qistoph** [comment]
You shouldn't publish any of your passwords, so you might want to edit the image and remove it.

Regarding your issue, is there any output in the log?

**Comment by JeroenV99** [comment]
where can i find the log output file, i am new with magicmirror

**Comment by qistoph** [comment]
You can find information on MagicMirror logs in the [docs online](https://github.com/MichMich/MagicMirror/wiki/Module-Debugging#logging).

If you need additional assistance, please explain exactly, in detail, the steps you've taken to install the module and to try and fix the issue.

**Comment by Rowdy2811** [comment]
Hello Gistoph,
First Nice Job ;0)
In the module on my screen i get "recieved data empty invalid"
I put my user and ww in the js file. where do you have to put the api key?
When i log in on NS there i get the file with the stations, 
In the logs i don't see anything strange.
My config file dont's have any issues. 
Hope you can put me in the right direction.
Rowdy

**Comment by stuiterberg** [comment]
I have the same issue as Rowdy2811. Maybe it's a new way for authentication. There is no username and password, just a Ocp-Apim-Subscription-Key. Correct me if i'm wrong.

Alex

**Comment by qistoph** [comment]
NS recently introduced a new API. This module is not yet updated to work with that API.  Please keep an eye on issue #13, for any progress.

I'm not sure if it's still possible to sign up for the old API at this time.

**Comment by qistoph** [comment]
Looking for beta testers. Please give v2 a try:

https://github.com/qistoph/MMM-nstreinen/tree/v2

If you find anything that isn't working or looks suspicious, please create an issue.
