### ISSUE TITLE
Error fetching station

### ISSUE THREAD

**Issue by SemicolonStruggles** [qistoph/MMM-nstreinen#18]
Related to #10 

Error fetching station when the device temporarily loses internet connection. Module does not recover on its own. Error persists until the module is rebooted.

Error:
Error fetching station: Error: getaddrinfo EAI_AGAIN webservices.ns.nl webservices.ns.nl:80

Reproduce:
Temporarily disable the wifi network that the device is connected to. (Cannot confirm this is also an issue with cable internet, but I assume it is.)

**Comment by qistoph** [comment]
Are you still experiencing this issue with the new V2 module? If so, could you re-open this issue, please?
