### ISSUE TITLE
"received data emppty or invalid"

### ISSUE THREAD

**Issue by Lex236** [qistoph/MMM-nstreinen#19]
Gisteren de module geïnstalleerd en toegang aangevraagd tot de NS travel informatie API, wanneer ik met mijn inloggegevens de API daar test krijg ik de stationsinformatie correct binnen, echter op mijn MagicMirror krijg ik de melding "Received data empty or invalid"

![image](https://user-images.githubusercontent.com/49805869/56454135-aba6a400-634c-11e9-86c6-8a336d95658f.png)

**Comment by Lex236** [comment]
![image](https://user-images.githubusercontent.com/49805869/56454173-19eb6680-634d-11e9-812d-885b5a82a8fc.png)

**Comment by Lex236** [comment]
![image](https://user-images.githubusercontent.com/49805869/56454200-751d5900-634d-11e9-928a-5903177fb05b.png)


Geen idee of deze vulnerabilities ermee te maken hebben, maar ik denk ik gooi alle informatie die ik heb hier maar neer ;p zelf geen tot weinig programmeerkennis, ben een leek

**Comment by qistoph** [comment]
NS recently introduced a new API. This module is not yet updated to work with that API.  Please keep an eye on issue #13, for any progress.

I'm not sure if it's still possible to sign up for the old API at this time.

**Comment by qistoph** [comment]
The new API is integrated in the master branch and should fix this issue for you.
