### ISSUE TITLE
Add parameter to display in the future

### ISSUE THREAD

**Issue by hermlam** [qistoph/MMM-nstreinen#2]
HI,
Great app, I have 2 instances on my mirror.
I have a future request. Is it possible to add paramater with a kind of delay in minutes. I need 10 minutes to get to the station, so I want to see the departures within 10 minutes. The current trains will already be gone when I arrive at the station.
Thanks!

Herman

**Comment by qistoph** [comment]
Good suggestion. I'll keep this issue open as a reminder and I'll try to work on it when I find some time.

Are you using the `master` or `develop` branch? The `develop` branch allows you to specify trains leaving a specific station for a specific destination. That might help you out in the mean time, to get the most relevant trains on your mirror.

**Comment by qistoph** [comment]
The NS API unfortunately doesn't allow fetching the 'Actuele Vertrektijden' with an offset:
http://www.ns.nl/reisinformatie/ns-api/documentatie-actuele-vertrektijden.html

For the 'Reisadviezen' (from station X - to station Y), it is possible to add it though:
http://www.ns.nl/reisinformatie/ns-api/documentatie-reisadviezen.html

**Comment by hermlam** [comment]
HI, thanks for finding out!
