### ISSUE TITLE
Error when specifying the arrival station: "Error fetching NS info: invalid API key"

### ISSUE THREAD

**Issue by RaspNewby** [qistoph/MMM-nstreinen#25]
Using only a departure station (without arrival station) works fine. Whenever I specify the arrival station, I get the "Error fetching NS info: invalid API key". Am I doing something wrong? Are other people facing the same issue?

`{
      		    module: 'nstreinen',
		    position: 'top_right',
		    header: 'Treinen',
		    config: {
         	      apiKey:'<MyKey>',
		      fromStation: 'GN',
		      toStation: 'UT'
		    }
		  },`

**Comment by qistoph** [comment]
Could you check which API subscription (abonnement) you're using?

This is available on the NS API website:
https://apiportal.ns.nl/developer

The old one "Public-Travel-Information-API" should no longer be used, you'll need to use an API key for "Ns-App". This can be requested at https://apiportal.ns.nl/products/NsApp.

**Comment by RaspNewby** [comment]
That was definitely the problem. Thanks man!
