### ISSUE TITLE
Keeps loading

### ISSUE THREAD

**Issue by bduijnhouwer** [qistoph/MMM-nstreinen#28]
Hi,

This module keeps loading on my mirror.
What am I doing wrong?

Bastiaan

**Comment by qistoph** [comment]
Sorry for the late response. Are you still having issues?

Could you share some more details?
- What's your config like
- Are there any messages in the logs

**Comment by bduijnhouwer** [comment]
Hi,

No, my problem is solved. I don't know why it did that.
Suddenly, it started working.

Maybe it took some time to download the data.

Thanx for your reply !
