### ISSUE TITLE
Error fetching NS info: invalid API key

### ISSUE THREAD

**Issue by MikieK-DH** [qistoph/MMM-nstreinen#29]
Hi,

Can you please help me? The screen keeps saying "Error fetching NS info: invalid API key"

<a href='https://www.mupload.nl/index/?ref=p5k8o66' border='0' target='_blank'><img src='https://www.mupload.nl/img/p5k8o66.png' border='0'></a>

I've got an API-key for "Public-Travel-Information" on https://apiportal.ns.nl/. Tried both primaire and secondaire key and also generated new ones. Do I have the wrong API?

<a href='https://www.mupload.nl/index/?ref=9zcjjs2opux' border='0' target='_blank'><img src='https://www.mupload.nl/img/9zcjjs2opux.png' border='0'></a>

The code is the one from the readme file:

`  {
    module: "nstreinen" ,
    position: " top_right" ,
    header: " Treinen vanaf Schiphol Airport" ,
    config: {
      apiKey: "xxxxxxxxxxxxxxxxxxxxxx",
      fromStation: "SHL"
    }
  },

Thank you,
Mike

**Comment by Willempy** [comment]
Same here, api key works in other platform.

**Comment by qistoph** [comment]
You're using the old API:
![image](https://user-images.githubusercontent.com/678500/81600369-c9b4cb80-93c9-11ea-857e-2da6af3a3699.png)

You need an API key for this one:
https://apiportal.ns.nl/Products/NsApp

It should show up as "Ns-App" in your profile:
![image](https://user-images.githubusercontent.com/678500/81600510-04b6ff00-93ca-11ea-88bf-a1cead8af893.png)

Feel free to re-open if it still won't work.

**Comment by Willempy** [comment]
My new api, on the new portal, was created yesterday.

**Comment by Willempy** [comment]
![image](https://user-images.githubusercontent.com/5405686/81604997-14861180-93d1-11ea-8ddb-69b828e684cb.jpeg)

**Comment by Willempy** [comment]
Problem found, wrong api key. Thanks!
