### ISSUE TITLE
Possibility to set multiple destinations

### ISSUE THREAD

**Issue by Elmardus** [qistoph/MMM-nstreinen#3]
I would love to have the possibility to set two stations as 'destination', and only show trains to those destinations. Might that be possible?

**Comment by qistoph** [comment]
You could add two modules. One with each destination and the same origin. Would that help you out?

**Comment by dionator** [comment]
@Elmardus Could you solve this? Need to find a way to this as well. 
Not really a power user yet, so can't tweak modules just yet.

**Comment by Elmardus** [comment]
I'm afraid I can't. I've looked into the code but couldn't figure out a way to do it, but I'm not a good programmer ;)

**Comment by dionator** [comment]
@Elmardus figured it out.
You can edit the nstreinen.js file and add your destination.
You'll find the file at  _MagicMirror>modules>nstreinen>nstreinen.js_ 
In my version the line is close to the top and it looks like this:
Module.register("nstreinen", {
	defaults: {
		destination: "Amsterdam", //this used to be Null.
	.....

**Comment by dionator** [comment]
@Elmardus or even better: just add destination:"your destination" on the config.js file :)

**Comment by qistoph** [comment]
For now I'm closing this issue, because @dionator seems to have fixed his issue and my previous question was not answered.

@Elmardus feel free to re-open this issue with a more specific description of the solution you're looking for.
