### ISSUE TITLE
symbolMapping goes wrong

### ISSUE THREAD

**Issue by HenkyB** [qistoph/MMM-nstreinen#48]
Did a new install, and now i got question marks instead of symbolMapping i guess.
So first the symbol of a train is shown, followed by space, then the question marks ??, and then the travel time between (), or Intercity + (traveltime).

Any Clue ?

**Comment by qistoph** [comment]
Sometimes NS introduces new types of transport descriptions. Like "bus" or "vervangend vervoer". Not all of these are mapped to symbols (yet).

If you manage to figure out the description to map and have a suggestion for the symbol, a PR is most welcome.

**Comment by HenkyB** [comment]
Hi Chris,

Received my PR ?
Did some researche,, not having any experience with NodeJs.
But i managed to find out that the 'nstreinen.js' lacked in the "LegRenaming" part the entry  "ST": "Stoptrein",
On the NS API website you can test your API key, getting an overview of the receiving tekst.
This wil not cost you tons of time to update your beautifull Module.

Regards Henk

**Comment by qistoph** [comment]
The PR hasn't reached me. Where did you create/send it?

**Comment by HenkyB** [comment]
Hi Chris,

Hope the list is complete.
I think, the symbols are not a big issue.
A train is a train, and it comes with a explanatory text.
Symbols can be obtained from the NS Web application ;-).

Regards, Henk

legRenaming: 
			"SPR":    "Sprinter",
			"IC":      "Intercity",
			"ICE":     "ICE Internationaal",
			"ICD":     "Intercity Direct",
			"NJ":      "Nightjet"
			"NSS":    "Snelbus"
			"ST":      "Stoptrein",
			"S":        "Sneltrein",
			"BUS":    "Stopbus i.p.v. trein",

symbolMapping:

Naam in NS planner	      	       icon     Mtschp

"NS Int ICE International"	      'train'  //NS int
'NS Int Intercity'			       'train'  //NS int
"NS Int Nightjet"			       'train'  //NS int
'Nightjet'					        'train'  //NS Int	
'NS Intercity':         		               'train'  //NS
'NS Sprinter':          		               'train'  //NS 
'Arriva Sneltrein':     		       'train'  //Arriva
'Arriva Stoptrein'			       'train'  //Arriva
'R-net Stoptrein':      		       'train'  //R-net
'R-net Sprinter':			       'train'  //R-net
'Valleilijn Stoptrein': 		       'train'  //connexion
'Blauwnet Sprinter':    		       'train'  //Blauwnet
'Blauwnet Sneltrein":   		       'train'  //Blauwnet
'Blauwnet Stoptrein':			'train'  //Blauwnet
'NMBS Stoptrein				'train'  //NMBS
'DB Stoptrein':         		        'train'  //DB Regio NRW
'VIAS Stoptrein':       		        'train'  //VIAS Rail GMBH
'Eurobahn Stoptrein':   		        'train'  //Eurobahn
'Eurobahn Sneltrein',			'train'  //Eurobahn
'Eurobahn Stopbus i.p.v. trein'	'bus'    //Eurobahn



Aansluitingen:

Type				Icon	

'Arriva Bus'                 'bus'         //Arriva
'RET Metro':                'metro'     //R'dam
'GVB Tram':                 'tram'       //A'dam
'RET Tram':                  'tram'       //R'dam
'GVB Veerdienst':        'ferry'       //A'dam
'Lopen':                       'walk'
'Fietsen':                      'bike' 
'Openbaar vervoer':     'bus'
'Auto':                          'auto'
'Bus':                            'bus'

**Comment by HenkyB** [comment]
Sorry,

The spaces are removed automaticly :-(.
