### ISSUE TITLE
OV Fiets counter

### ISSUE THREAD

**Issue by SamBouwer** [qistoph/MMM-nstreinen#5]
It would be cool to show the amount of available public transport bikes (OV Fietsen) for the selected train station. This data is available in json format at http://fiets.openov.nl/locaties.json, but I have insufficient knowledge about javascript to build this in to your existing version. Is this something you could implement?

**Comment by qistoph** [comment]
Hi Sam,

Thanks for you message. I do agree that the number of available bikes would be a nice feature to show on a mirror. However, I don't see a fit in this module.

Maybe it's worth a separate module to show just the number of bikes at a (or multiple) station(s).

**Comment by SamBouwer** [comment]
Hi! Thank you for your response :)
