### ISSUE TITLE
No helper found for module: nstreinen.

### ISSUE THREAD

**Issue by FFabioGIT** [qistoph/MMM-nstreinen#7]
So I tried to load up the nstreinen module but it doesn't seem to work. It is showing that it needs a helper. I am new to using a Raspberry Pi so I'm not sure if I'm doing something wrong. I tested a other 3rd party Module and that one is working fine for me.

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.3.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.3.1
Loading config ...
Loading module helpers ...
No helper found for module: nstreinen.

does anyone know how to fix this issue?

**Comment by qistoph** [comment]
Did you follow all instructions exactly as specified in the readme under "Installing the module"?

Could you show an "ls -al" of your modules directory and inside the nstreinen-module?

**Comment by qistoph** [comment]
Closing due to now response.
